
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BalanceDropdown': typeof import("../components/BalanceDropdown.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'ForgotPassword': typeof import("../components/ForgotPassword.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'LoginMenu': typeof import("../components/LoginMenu.vue")['default']
    'MainMobileNav': typeof import("../components/MainMobileNav.vue")['default']
    'MobileNav': typeof import("../components/MobileNav.vue")['default']
    'NFTexLogo': typeof import("../components/NFTexLogo.vue")['default']
    'NFTexLogoMini': typeof import("../components/NFTexLogoMini.vue")['default']
    'Navbar': typeof import("../components/Navbar.vue")['default']
    'Toast': typeof import("../components/Toast.vue")['default']
    'UserDropdown': typeof import("../components/UserDropdown.vue")['default']
    'AdminAsideBar': typeof import("../components/admin/AsideBar.vue")['default']
    'AdminBalance': typeof import("../components/admin/Balance.vue")['default']
    'AdminHeader': typeof import("../components/admin/Header.vue")['default']
    'AdminMobileNavBar': typeof import("../components/admin/MobileNavBar.vue")['default']
    'AdminNotifications': typeof import("../components/admin/Notifications.vue")['default']
    'AdminSideBar': typeof import("../components/admin/SideBar.vue")['default']
    'AdminTopUpWithEmail': typeof import("../components/admin/TopUpWithEmail.vue")['default']
    'AdminUser': typeof import("../components/admin/User.vue")['default']
    'AdminUserMenuDropdown': typeof import("../components/admin/UserMenuDropdown.vue")['default']
    'AdminNotificationEntry': typeof import("../components/admin/notification/Entry.vue")['default']
    'AdminSettingsDeactivate': typeof import("../components/admin/settings/deactivate.vue")['default']
    'AdminSettingsEmail': typeof import("../components/admin/settings/email.vue")['default']
    'AdminSettingsLoginSessions': typeof import("../components/admin/settings/loginSessions.vue")['default']
    'AdminSettingsNotification': typeof import("../components/admin/settings/notification.vue")['default']
    'AdminTransactionEntry': typeof import("../components/admin/transaction/Entry.vue")['default']
    'AdminTransactionKeypad': typeof import("../components/admin/transaction/Keypad.vue")['default']
    'AdminUserNotify': typeof import("../components/admin/user/Notify.vue")['default']
    'AdminUserProfile': typeof import("../components/admin/user/Profile.vue")['default']
    'AdminUserTransaction': typeof import("../components/admin/user/Transaction.vue")['default']
    'AdminUsersNewUser': typeof import("../components/admin/users/NewUser.vue")['default']
    'AdminUsersUser': typeof import("../components/admin/users/User.vue")['default']
    'AppAsideBar': typeof import("../components/app/AsideBar.vue")['default']
    'AppBalance': typeof import("../components/app/Balance.vue")['default']
    'AppHeader': typeof import("../components/app/Header.vue")['default']
    'AppMobileNavBar': typeof import("../components/app/MobileNavBar.vue")['default']
    'AppNotifications': typeof import("../components/app/Notifications.vue")['default']
    'AppSideBar': typeof import("../components/app/SideBar.vue")['default']
    'AppTopUp': typeof import("../components/app/TopUp.vue")['default']
    'AppUpgradeAccount': typeof import("../components/app/UpgradeAccount.vue")['default']
    'AppUserMenuDropdown': typeof import("../components/app/UserMenuDropdown.vue")['default']
    'AppNotificationEntry': typeof import("../components/app/notification/Entry.vue")['default']
    'AppScanCamera': typeof import("../components/app/scan/Camera.vue")['default']
    'AppSettingsDeactivate': typeof import("../components/app/settings/deactivate.vue")['default']
    'AppSettingsEmail': typeof import("../components/app/settings/email.vue")['default']
    'AppSettingsLoginSessions': typeof import("../components/app/settings/loginSessions.vue")['default']
    'AppSettingsNotification': typeof import("../components/app/settings/notification.vue")['default']
    'AppTransactionEntry': typeof import("../components/app/transaction/Entry.vue")['default']
    'AppTransactionKeypad': typeof import("../components/app/transaction/Keypad.vue")['default']
    'AppTransactionToBank': typeof import("../components/app/transaction/ToBank.vue")['default']
    'AppTransactionToElisa': typeof import("../components/app/transaction/ToElisa.vue")['default']
    'SwiperMainSlide': typeof import("../components/swiper/MainSlide.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBalanceDropdown': typeof import("../components/BalanceDropdown.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyForgotPassword': typeof import("../components/ForgotPassword.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyLoginMenu': typeof import("../components/LoginMenu.vue")['default']
    'LazyMainMobileNav': typeof import("../components/MainMobileNav.vue")['default']
    'LazyMobileNav': typeof import("../components/MobileNav.vue")['default']
    'LazyNFTexLogo': typeof import("../components/NFTexLogo.vue")['default']
    'LazyNFTexLogoMini': typeof import("../components/NFTexLogoMini.vue")['default']
    'LazyNavbar': typeof import("../components/Navbar.vue")['default']
    'LazyToast': typeof import("../components/Toast.vue")['default']
    'LazyUserDropdown': typeof import("../components/UserDropdown.vue")['default']
    'LazyAdminAsideBar': typeof import("../components/admin/AsideBar.vue")['default']
    'LazyAdminBalance': typeof import("../components/admin/Balance.vue")['default']
    'LazyAdminHeader': typeof import("../components/admin/Header.vue")['default']
    'LazyAdminMobileNavBar': typeof import("../components/admin/MobileNavBar.vue")['default']
    'LazyAdminNotifications': typeof import("../components/admin/Notifications.vue")['default']
    'LazyAdminSideBar': typeof import("../components/admin/SideBar.vue")['default']
    'LazyAdminTopUpWithEmail': typeof import("../components/admin/TopUpWithEmail.vue")['default']
    'LazyAdminUser': typeof import("../components/admin/User.vue")['default']
    'LazyAdminUserMenuDropdown': typeof import("../components/admin/UserMenuDropdown.vue")['default']
    'LazyAdminNotificationEntry': typeof import("../components/admin/notification/Entry.vue")['default']
    'LazyAdminSettingsDeactivate': typeof import("../components/admin/settings/deactivate.vue")['default']
    'LazyAdminSettingsEmail': typeof import("../components/admin/settings/email.vue")['default']
    'LazyAdminSettingsLoginSessions': typeof import("../components/admin/settings/loginSessions.vue")['default']
    'LazyAdminSettingsNotification': typeof import("../components/admin/settings/notification.vue")['default']
    'LazyAdminTransactionEntry': typeof import("../components/admin/transaction/Entry.vue")['default']
    'LazyAdminTransactionKeypad': typeof import("../components/admin/transaction/Keypad.vue")['default']
    'LazyAdminUserNotify': typeof import("../components/admin/user/Notify.vue")['default']
    'LazyAdminUserProfile': typeof import("../components/admin/user/Profile.vue")['default']
    'LazyAdminUserTransaction': typeof import("../components/admin/user/Transaction.vue")['default']
    'LazyAdminUsersNewUser': typeof import("../components/admin/users/NewUser.vue")['default']
    'LazyAdminUsersUser': typeof import("../components/admin/users/User.vue")['default']
    'LazyAppAsideBar': typeof import("../components/app/AsideBar.vue")['default']
    'LazyAppBalance': typeof import("../components/app/Balance.vue")['default']
    'LazyAppHeader': typeof import("../components/app/Header.vue")['default']
    'LazyAppMobileNavBar': typeof import("../components/app/MobileNavBar.vue")['default']
    'LazyAppNotifications': typeof import("../components/app/Notifications.vue")['default']
    'LazyAppSideBar': typeof import("../components/app/SideBar.vue")['default']
    'LazyAppTopUp': typeof import("../components/app/TopUp.vue")['default']
    'LazyAppUpgradeAccount': typeof import("../components/app/UpgradeAccount.vue")['default']
    'LazyAppUserMenuDropdown': typeof import("../components/app/UserMenuDropdown.vue")['default']
    'LazyAppNotificationEntry': typeof import("../components/app/notification/Entry.vue")['default']
    'LazyAppScanCamera': typeof import("../components/app/scan/Camera.vue")['default']
    'LazyAppSettingsDeactivate': typeof import("../components/app/settings/deactivate.vue")['default']
    'LazyAppSettingsEmail': typeof import("../components/app/settings/email.vue")['default']
    'LazyAppSettingsLoginSessions': typeof import("../components/app/settings/loginSessions.vue")['default']
    'LazyAppSettingsNotification': typeof import("../components/app/settings/notification.vue")['default']
    'LazyAppTransactionEntry': typeof import("../components/app/transaction/Entry.vue")['default']
    'LazyAppTransactionKeypad': typeof import("../components/app/transaction/Keypad.vue")['default']
    'LazyAppTransactionToBank': typeof import("../components/app/transaction/ToBank.vue")['default']
    'LazyAppTransactionToElisa': typeof import("../components/app/transaction/ToElisa.vue")['default']
    'LazySwiperMainSlide': typeof import("../components/swiper/MainSlide.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BalanceDropdown: typeof import("../components/BalanceDropdown.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const ForgotPassword: typeof import("../components/ForgotPassword.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const LoginMenu: typeof import("../components/LoginMenu.vue")['default']
export const MainMobileNav: typeof import("../components/MainMobileNav.vue")['default']
export const MobileNav: typeof import("../components/MobileNav.vue")['default']
export const NFTexLogo: typeof import("../components/NFTexLogo.vue")['default']
export const NFTexLogoMini: typeof import("../components/NFTexLogoMini.vue")['default']
export const Navbar: typeof import("../components/Navbar.vue")['default']
export const Toast: typeof import("../components/Toast.vue")['default']
export const UserDropdown: typeof import("../components/UserDropdown.vue")['default']
export const AdminAsideBar: typeof import("../components/admin/AsideBar.vue")['default']
export const AdminBalance: typeof import("../components/admin/Balance.vue")['default']
export const AdminHeader: typeof import("../components/admin/Header.vue")['default']
export const AdminMobileNavBar: typeof import("../components/admin/MobileNavBar.vue")['default']
export const AdminNotifications: typeof import("../components/admin/Notifications.vue")['default']
export const AdminSideBar: typeof import("../components/admin/SideBar.vue")['default']
export const AdminTopUpWithEmail: typeof import("../components/admin/TopUpWithEmail.vue")['default']
export const AdminUser: typeof import("../components/admin/User.vue")['default']
export const AdminUserMenuDropdown: typeof import("../components/admin/UserMenuDropdown.vue")['default']
export const AdminNotificationEntry: typeof import("../components/admin/notification/Entry.vue")['default']
export const AdminSettingsDeactivate: typeof import("../components/admin/settings/deactivate.vue")['default']
export const AdminSettingsEmail: typeof import("../components/admin/settings/email.vue")['default']
export const AdminSettingsLoginSessions: typeof import("../components/admin/settings/loginSessions.vue")['default']
export const AdminSettingsNotification: typeof import("../components/admin/settings/notification.vue")['default']
export const AdminTransactionEntry: typeof import("../components/admin/transaction/Entry.vue")['default']
export const AdminTransactionKeypad: typeof import("../components/admin/transaction/Keypad.vue")['default']
export const AdminUserNotify: typeof import("../components/admin/user/Notify.vue")['default']
export const AdminUserProfile: typeof import("../components/admin/user/Profile.vue")['default']
export const AdminUserTransaction: typeof import("../components/admin/user/Transaction.vue")['default']
export const AdminUsersNewUser: typeof import("../components/admin/users/NewUser.vue")['default']
export const AdminUsersUser: typeof import("../components/admin/users/User.vue")['default']
export const AppAsideBar: typeof import("../components/app/AsideBar.vue")['default']
export const AppBalance: typeof import("../components/app/Balance.vue")['default']
export const AppHeader: typeof import("../components/app/Header.vue")['default']
export const AppMobileNavBar: typeof import("../components/app/MobileNavBar.vue")['default']
export const AppNotifications: typeof import("../components/app/Notifications.vue")['default']
export const AppSideBar: typeof import("../components/app/SideBar.vue")['default']
export const AppTopUp: typeof import("../components/app/TopUp.vue")['default']
export const AppUpgradeAccount: typeof import("../components/app/UpgradeAccount.vue")['default']
export const AppUserMenuDropdown: typeof import("../components/app/UserMenuDropdown.vue")['default']
export const AppNotificationEntry: typeof import("../components/app/notification/Entry.vue")['default']
export const AppScanCamera: typeof import("../components/app/scan/Camera.vue")['default']
export const AppSettingsDeactivate: typeof import("../components/app/settings/deactivate.vue")['default']
export const AppSettingsEmail: typeof import("../components/app/settings/email.vue")['default']
export const AppSettingsLoginSessions: typeof import("../components/app/settings/loginSessions.vue")['default']
export const AppSettingsNotification: typeof import("../components/app/settings/notification.vue")['default']
export const AppTransactionEntry: typeof import("../components/app/transaction/Entry.vue")['default']
export const AppTransactionKeypad: typeof import("../components/app/transaction/Keypad.vue")['default']
export const AppTransactionToBank: typeof import("../components/app/transaction/ToBank.vue")['default']
export const AppTransactionToElisa: typeof import("../components/app/transaction/ToElisa.vue")['default']
export const SwiperMainSlide: typeof import("../components/swiper/MainSlide.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBalanceDropdown: typeof import("../components/BalanceDropdown.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyForgotPassword: typeof import("../components/ForgotPassword.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyLoginMenu: typeof import("../components/LoginMenu.vue")['default']
export const LazyMainMobileNav: typeof import("../components/MainMobileNav.vue")['default']
export const LazyMobileNav: typeof import("../components/MobileNav.vue")['default']
export const LazyNFTexLogo: typeof import("../components/NFTexLogo.vue")['default']
export const LazyNFTexLogoMini: typeof import("../components/NFTexLogoMini.vue")['default']
export const LazyNavbar: typeof import("../components/Navbar.vue")['default']
export const LazyToast: typeof import("../components/Toast.vue")['default']
export const LazyUserDropdown: typeof import("../components/UserDropdown.vue")['default']
export const LazyAdminAsideBar: typeof import("../components/admin/AsideBar.vue")['default']
export const LazyAdminBalance: typeof import("../components/admin/Balance.vue")['default']
export const LazyAdminHeader: typeof import("../components/admin/Header.vue")['default']
export const LazyAdminMobileNavBar: typeof import("../components/admin/MobileNavBar.vue")['default']
export const LazyAdminNotifications: typeof import("../components/admin/Notifications.vue")['default']
export const LazyAdminSideBar: typeof import("../components/admin/SideBar.vue")['default']
export const LazyAdminTopUpWithEmail: typeof import("../components/admin/TopUpWithEmail.vue")['default']
export const LazyAdminUser: typeof import("../components/admin/User.vue")['default']
export const LazyAdminUserMenuDropdown: typeof import("../components/admin/UserMenuDropdown.vue")['default']
export const LazyAdminNotificationEntry: typeof import("../components/admin/notification/Entry.vue")['default']
export const LazyAdminSettingsDeactivate: typeof import("../components/admin/settings/deactivate.vue")['default']
export const LazyAdminSettingsEmail: typeof import("../components/admin/settings/email.vue")['default']
export const LazyAdminSettingsLoginSessions: typeof import("../components/admin/settings/loginSessions.vue")['default']
export const LazyAdminSettingsNotification: typeof import("../components/admin/settings/notification.vue")['default']
export const LazyAdminTransactionEntry: typeof import("../components/admin/transaction/Entry.vue")['default']
export const LazyAdminTransactionKeypad: typeof import("../components/admin/transaction/Keypad.vue")['default']
export const LazyAdminUserNotify: typeof import("../components/admin/user/Notify.vue")['default']
export const LazyAdminUserProfile: typeof import("../components/admin/user/Profile.vue")['default']
export const LazyAdminUserTransaction: typeof import("../components/admin/user/Transaction.vue")['default']
export const LazyAdminUsersNewUser: typeof import("../components/admin/users/NewUser.vue")['default']
export const LazyAdminUsersUser: typeof import("../components/admin/users/User.vue")['default']
export const LazyAppAsideBar: typeof import("../components/app/AsideBar.vue")['default']
export const LazyAppBalance: typeof import("../components/app/Balance.vue")['default']
export const LazyAppHeader: typeof import("../components/app/Header.vue")['default']
export const LazyAppMobileNavBar: typeof import("../components/app/MobileNavBar.vue")['default']
export const LazyAppNotifications: typeof import("../components/app/Notifications.vue")['default']
export const LazyAppSideBar: typeof import("../components/app/SideBar.vue")['default']
export const LazyAppTopUp: typeof import("../components/app/TopUp.vue")['default']
export const LazyAppUpgradeAccount: typeof import("../components/app/UpgradeAccount.vue")['default']
export const LazyAppUserMenuDropdown: typeof import("../components/app/UserMenuDropdown.vue")['default']
export const LazyAppNotificationEntry: typeof import("../components/app/notification/Entry.vue")['default']
export const LazyAppScanCamera: typeof import("../components/app/scan/Camera.vue")['default']
export const LazyAppSettingsDeactivate: typeof import("../components/app/settings/deactivate.vue")['default']
export const LazyAppSettingsEmail: typeof import("../components/app/settings/email.vue")['default']
export const LazyAppSettingsLoginSessions: typeof import("../components/app/settings/loginSessions.vue")['default']
export const LazyAppSettingsNotification: typeof import("../components/app/settings/notification.vue")['default']
export const LazyAppTransactionEntry: typeof import("../components/app/transaction/Entry.vue")['default']
export const LazyAppTransactionKeypad: typeof import("../components/app/transaction/Keypad.vue")['default']
export const LazyAppTransactionToBank: typeof import("../components/app/transaction/ToBank.vue")['default']
export const LazyAppTransactionToElisa: typeof import("../components/app/transaction/ToElisa.vue")['default']
export const LazySwiperMainSlide: typeof import("../components/swiper/MainSlide.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
